### ISSUE TITLE
received error 

### ISSUE THREAD

**Issue by reza2981905** [cmazzoni87/ComputerVisionRegression#1]
there is no timeseries_to_gaf library

**Comment by q-learning-trader** [comment]
I think is using IBM stock share data @reza2981905 . You can download from Yahoo.

**Comment by cmazzoni87** [comment]
@reza2981905 refer yourself to the script named as such on the project.

**Comment by cmazzoni87** [comment]
'@q-learning-trader you can get a sample of intraday data from this website: http://www.kibot.com/free_historical_data.aspx

**Comment by q-learning-trader** [comment]
Thanks @cmazzoni87 . I had a quick look to the paper today and I found that are normalizing data with min/max.
Are you doing the same?
